apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::799345568171:role/eksctl-cluster-26-nodegroup-spot-NodeInstanceRole-sQiBI0BoCoJZ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | # this block is added and made changes as per our requirement.
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::799345568171:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-12T12:13:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1232"
  uid: 2a4b40ad-3e7b-4736-86fc-ee7869827b78
